[options]
admin_passwd = $admin_passwd
xmlrpc_port = 8069
db_host = db
db_user = odoo
db_password = password
db_port = 5432
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extras-addons
db_name = postgres